"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /KWin
Bus name   : org.kde.KWin
"""

from jeepney.wrappers import MessageGenerator, new_method_call


class KWin(MessageGenerator):
    interface = 'org.kde.KWin'

    def __init__(self, object_path='/KWin',
                 bus_name='org.kde.KWin'):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def cascadeDesktop(self):
        return new_method_call(self, 'cascadeDesktop')

    def unclutterDesktop(self):
        return new_method_call(self, 'unclutterDesktop')

    def reconfigure(self):
        return new_method_call(self, 'reconfigure')

    def killWindow(self):
        return new_method_call(self, 'killWindow')

    def setCurrentDesktop(self, desktop):
        return new_method_call(self, 'setCurrentDesktop', 'i',
                               (desktop,))

    def currentDesktop(self):
        return new_method_call(self, 'currentDesktop')

    def nextDesktop(self):
        return new_method_call(self, 'nextDesktop')

    def previousDesktop(self):
        return new_method_call(self, 'previousDesktop')

    def stopActivity(self, arg0):
        return new_method_call(self, 'stopActivity', 's',
                               (arg0,))

    def startActivity(self, arg0):
        return new_method_call(self, 'startActivity', 's',
                               (arg0,))

    def supportInformation(self):
        return new_method_call(self, 'supportInformation')

    def activeOutputName(self):
        return new_method_call(self, 'activeOutputName')

    def showDebugConsole(self):
        return new_method_call(self, 'showDebugConsole')

    def replace(self):
        return new_method_call(self, 'replace')

    def queryWindowInfo(self):
        return new_method_call(self, 'queryWindowInfo')

    def getWindowInfo(self, arg0):
        return new_method_call(self, 'getWindowInfo', 's',
                               (arg0,))

    def showDesktop(self, showing):
        return new_method_call(self, 'showDesktop', 'b',
                               (showing,))
